name: LDPlugins
main: org.lastdesire.ldplugins.LDPlugins
version: 1.1.0
authors: [lastdesire19]

commands:
  listen:
    description: Ah! I've got you!
    usage: /<command>
  dejavu:
    usage: /<command> [start | watch | unwatch]

permissions:
  SimpleChestListenerPlugin.command.*:
    description: Allow you to track chestopening histories.
    default: true